<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Fundamentos de Aprendizado de Máquina
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Teoria;</li>
  <li>Atributos categóricos;</li>
  <li>Atributos numéricos;</li>
  <li>Dados faltantes.</li>
</ol>

---

# **Exercícios**

## 1\. Pinguins

Neste exercício, vamos utilizar uma base de dados com informações sobre penguins. A idéia é preparar a base de dados para prever a espécie do penguin (variável resposta) baseado em suas características físicas e geográficas (variáveis preditivas).

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
data = sns.load_dataset('penguins')

In [3]:
data.head(50
          )

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,Female
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male
15,Adelie,Torgersen,36.6,17.8,185.0,3700.0,Female
16,Adelie,Torgersen,38.7,19.0,195.0,3450.0,Female
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,Male
18,Adelie,Torgersen,34.4,18.4,184.0,3325.0,Female
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,Male
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,Female
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,Male
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,Female
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,Male
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,Male
25,Adelie,Biscoe,35.3,18.9,187.0,3800.0,Female
26,Adelie,Biscoe,40.6,18.6,183.0,3550.0,Male
27,Adelie,Biscoe,40.5,17.9,187.0,3200.0,Female
28,Adelie,Biscoe,37.9,18.6,172.0,3150.0,Female
29,Adelie,Biscoe,40.5,18.9,180.0,3950.0,Male
30,Adelie,Dream,39.5,16.7,178.0,3250.0,Female
31,Adelie,Dream,37.2,18.1,178.0,3900.0,Male
32,Adelie,Dream,39.5,17.8,188.0,3300.0,Female
33,Adelie,Dream,40.9,18.9,184.0,3900.0,Male
34,Adelie,Dream,36.4,17.0,195.0,3325.0,Female
35,Adelie,Dream,39.2,21.1,196.0,4150.0,Male
36,Adelie,Dream,38.8,20.0,190.0,3950.0,Male
37,Adelie,Dream,42.2,18.5,180.0,3550.0,Female
38,Adelie,Dream,37.6,19.3,181.0,3300.0,Female
39,Adelie,Dream,39.8,19.1,184.0,4650.0,Male
40,Adelie,Dream,36.5,18.0,182.0,3150.0,Female
41,Adelie,Dream,40.8,18.4,195.0,3900.0,Male
42,Adelie,Dream,36.0,18.5,186.0,3100.0,Female
43,Adelie,Dream,44.1,19.7,196.0,4400.0,Male
44,Adelie,Dream,37.0,16.9,185.0,3000.0,Female
45,Adelie,Dream,39.6,18.8,190.0,4600.0,Male
46,Adelie,Dream,41.1,19.0,182.0,3425.0,Male
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
48,Adelie,Dream,36.0,17.9,190.0,3450.0,Female
49,Adelie,Dream,42.3,21.2,191.0,4150.0,Male

### **1.1. Valores nulos**

A base de dados possui valores faltantes, utilize os conceitos da aula para trata-los.

In [4]:
# resposta da questão 1.1

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [5]:
data.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [6]:
data = data.dropna(how='any', axis= 0)
data.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

### **1.2. Variáveis numéricas**

Identifique as variáveis numéricas e crie uma nova coluna **padronizando** seus valores. A nova coluna deve ter o mesmo nome da coluna original acrescidade de "*_std*".

> **Nota**: Você não deve tratar a variável resposta.

In [7]:
# resposta da questão 1.2

def padronizar_coluna(data, nome_coluna):

    media = data[nome_coluna].mean()
    desvio_padrao = data[nome_coluna].std()

    data[f"{nome_coluna}_std"] = data[nome_coluna].apply(lambda x: (x - media) / desvio_padrao)

    return data

In [8]:
# Aplicando a função às suas colunas
data = padronizar_coluna(data, 'bill_length_mm')
data = padronizar_coluna(data, 'bill_depth_mm')
data = padronizar_coluna(data, 'body_mass_g')
data = padronizar_coluna(data, 'flipper_length_mm')

data.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std,bill_depth_mm_std,body_mass_g_std,flipper_length_mm_std
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695,0.779559,-0.567621,-1.424608
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552,0.119404,-0.505525,-1.067867
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264,0.424091,-1.188572,-0.425733
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559,1.084246,-0.940192,-0.568429
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123,1.744400,-0.691811,-0.782474

### **1.3. Variáveis categóricas**

Identifique as variáveis categóricas nominais e ordinais, crie uma nova coluna aplicando a técnica correta de conversão a seus valores. A nova coluna deve ter o mesmo nome da coluna original acrescidade de "*_nom*" ou "*_ord*".

> **Nota**: Você não deve tratar a variável resposta.

In [9]:
# resposta da questão 1.3
# atributo categorico nominal
data[['sex']].head()

# usando a tecnica de codificacao chamada 'one hot encoding'.
data['sex_m_nom'] = data['sex'].apply(lambda sex: 1 if sex == 'Male' else 0)
data['sex_f_nom'] = data['sex'].apply(lambda sex: 1 if sex == 'Female' else 0)

data.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std,bill_depth_mm_std,body_mass_g_std,flipper_length_mm_std,sex_m_nom,sex_f_nom
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695,0.779559,-0.567621,-1.424608,1,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552,0.119404,-0.505525,-1.067867,0,1
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264,0.424091,-1.188572,-0.425733,0,1
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559,1.084246,-0.940192,-0.568429,0,1
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123,1.744400,-0.691811,-0.782474,1,0

In [12]:
# atributo categorico nominal

data[["island"]].head()

data['island'].drop_duplicates()

# classificando as ilhas presente no atributo "island"

data['island_torgersen_nom'] = data['island'].apply(lambda x: 1 if x == 'Torgersen' else 0)
data['island_biscoe_nom'] = data['island'].apply(lambda x: 1 if x == 'Biscoe' else 0)
data['island_dream_nom'] = data['island'].apply(lambda x: 1 if x == 'Dream' else 0)


data.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std,bill_depth_mm_std,body_mass_g_std,flipper_length_mm_std,sex_m_nom,sex_f_nom,island_torgersen_nom,island_biscoe_nom,island_dream_nom
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.894695,0.779559,-0.567621,-1.424608,1,0,1,0,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,-0.821552,0.119404,-0.505525,-1.067867,0,1,1,0,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,-0.675264,0.424091,-1.188572,-0.425733,0,1,1,0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,-1.333559,1.084246,-0.940192,-0.568429,0,1,1,0,0
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,-0.858123,1.744400,-0.691811,-0.782474,1,0,1,0,0

### **1.4. Limpeza**

Descarte as colunas originais e mantenha apenas a variável resposta e as variáveis preditivas com o sufixo *_std*", *_nom*" e "*_ord*".

In [13]:
# resposta da questão 1.4
data.drop(["island","bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g", "sex"], axis=1)

,species,bill_length_mm_std,bill_depth_mm_std,body_mass_g_std,flipper_length_mm_std,sex_m_nom,sex_f_nom,island_torgersen_nom,island_biscoe_nom,island_dream_nom
0,Adelie,-0.894695,0.779559,-0.567621,-1.424608,1,0,1,0,0
1,Adelie,-0.821552,0.119404,-0.505525,-1.067867,0,1,1,0,0
2,Adelie,-0.675264,0.424091,-1.188572,-0.425733,0,1,1,0,0
4,Adelie,-1.333559,1.084246,-0.940192,-0.568429,0,1,1,0,0
5,Adelie,-0.858123,1.744400,-0.691811,-0.782474,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
338,Gentoo,0.586470,-1.759497,0.891616,0.929884,0,1,0,1,0
340,Gentoo,0.513326,-1.454811,0.798473,1.001232,0,1,0,1,0
341,Gentoo,1.171621,-0.743875,1.916186,1.500670,1,0,0,1,0
342,Gentoo,0.220750,-1.200905,1.233139,0.787187,0,1,0,1,0
343,Gentoo,1.080191,-0.540750,1.481520,0.858536,1,0,0,1,0

---